import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/provider/global";
import Footer from "@/components/shared/footer/footer";
import NewsLetter from "@/components/shared/newsletter/newsletter";
import Navbar from "@/components/shared/common/navbar/navbar";
import Dropdown from "@/components/shared/common/navbar/dropdown";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <Navbar />
          <Dropdown></Dropdown>
          <div className="pb-28">{children}</div>
          <div className="px-[2%] md:px-[6%] bg-card-dark border border-card-dark">
            <NewsLetter />
            <div className="mt-20">
              <Footer />
            </div>
          </div>
        </GlobalProvider>
      </body>
    </html>
  );
}
